name: E2E Tests with Allure Reports

on:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM UTC
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      publish-to-pages:
        description: 'Publish reports to GitHub Pages'
        required: false
        default: false
        type: boolean

jobs:
  check-version:
    uses: ./.github/workflows/check-versions.yml

  # Test jobs using the enhanced workflow
  test-nextjs:
    name: "Next.js App with Allure Report"
    needs: check-version
    uses: ./.github/workflows/allure-report-publish.yml
    with:
      project-path: packages/civic-auth/nextjs
      playwright-spec: playwright/tests/nextjs-login.spec.ts
      browser: chromium
      publish-to-pages: ${{ github.event.inputs.publish-to-pages == 'true' || github.ref == 'refs/heads/main' }}
    secrets: inherit

  test-reactjs:
    name: "React.js App with Allure Report"
    needs: check-version
    uses: ./.github/workflows/allure-report-publish.yml
    with:
      project-path: packages/civic-auth/reactjs
      playwright-spec: playwright/tests/reactjs-login.spec.ts
      browser: firefox
      publish-to-pages: false  # Only publish main branch and manual triggers
    secrets: inherit

  test-express:
    name: "Express App with Allure Report"
    needs: check-version
    uses: ./.github/workflows/allure-report-publish.yml
    with:
      project-path: packages/civic-auth/server/express
      playwright-spec: playwright/tests/express-login.spec.ts
      browser: webkit
      publish-to-pages: false
    secrets: inherit

  # Example of Safari testing with Allure
  test-safari-comprehensive:
    name: "Safari Tests with Allure (Main Apps)"
    needs: check-version
    strategy:
      matrix:
        include:
          - project: packages/civic-auth/nextjs
            spec: playwright/tests/nextjs-login.spec.ts
            name: "Next.js Safari"
          - project: packages/civic-auth/reactjs  
            spec: playwright/tests/reactjs-login.spec.ts
            name: "React.js Safari"
          - project: packages/civic-auth/server/express
            spec: playwright/tests/express-login.spec.ts
            name: "Express Safari"
    uses: ./.github/workflows/allure-report-publish.yml
    with:
      project-path: ${{ matrix.project }}
      playwright-spec: ${{ matrix.spec }}
      browser: webkit
      publish-to-pages: false
    secrets: inherit

  # Aggregate and publish combined report (only on main branch)
  publish-combined-report:
    name: "Publish Combined Allure Report"
    needs: [test-nextjs, test-reactjs, test-express]
    if: ${{ github.ref == 'refs/heads/main' || github.event.inputs.publish-to-pages == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Download all Allure results
        uses: actions/download-artifact@v4
        with:
          pattern: allure-results-*
          path: combined-results

      - name: Combine Allure results
        run: |
          mkdir -p allure-results
          find combined-results -name "*.json" -exec cp {} allure-results/ \;
          find combined-results -name "*.txt" -exec cp {} allure-results/ \;
          find combined-results -name "*.png" -exec cp {} allure-results/ \;
          find combined-results -name "*.jpg" -exec cp {} allure-results/ \;

      - name: Load test report history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build combined test report
        uses: simple-elf/allure-report-action@master
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish combined test report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
