name: Build and run example apps using latest sdk versions

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  # push:
  # pull_request:
  workflow_dispatch:
    
jobs:
  check-version:
    uses: ./.github/workflows/check-versions.yml

  # Production jobs
  job-nextjs-example-app:
    name: "Nextjs example app"
    needs: check-version
    uses: ./.github/workflows/test-example-app.yml
    with:
      project-path: packages/civic-auth/nextjs
      cypress-spec: |
        cypress/e2e/features/example-apps/nextjs-login.feature
        cypress/e2e/features/example-apps/nextjs-custom-login.feature
    secrets: inherit

  job-nextjs-login-success-url:
    name: "Nextjs example app (with loginSuccessUrl)"
    needs: check-version
    uses: ./.github/workflows/test-login-success-url.yml
    secrets: inherit

  job-reactjs-example-app:
    name: "Reactjs example app"
    needs: check-version
    uses: ./.github/workflows/test-example-app.yml
    with:
      project-path: packages/civic-auth/reactjs
      cypress-spec: |
        cypress/e2e/features/example-apps/reactjs-login.feature
        cypress/e2e/features/example-apps/reactjs-custom-login.feature
    secrets: inherit

  job-express-example-app:
    name: "Express example app"
    needs: check-version
    uses: ./.github/workflows/test-example-app.yml
    with:
      project-path: packages/civic-auth/server/express
      cypress-spec: cypress/e2e/features/example-apps/express-login.feature
    secrets: inherit

  job-fastify-example-app:
    name: "Fastify example app"
    needs: check-version
    uses: ./.github/workflows/test-example-app.yml
    with:
      project-path: packages/civic-auth/server/fastify
      cypress-spec: cypress/e2e/features/example-apps/fastify-login.feature
    secrets: inherit

  job-hono-example-app:
    name: "Hono example app"
    needs: check-version
    uses: ./.github/workflows/test-example-app.yml
    with:
      project-path: packages/civic-auth/server/hono
      cypress-spec: cypress/e2e/features/example-apps/hono-login.feature
    secrets: inherit

  job-next-14-webpack-solana-wallet-adapter:
    name: "Next14 webpack Solana wallet adapter"
    needs: check-version
    uses: ./.github/workflows/test-example-app.yml
    with:
      project-path: packages/civic-auth-web3/solana/next14-wallet-adapter
      cypress-spec: cypress/e2e/features/example-apps/solana-next14-wa-login.feature
    secrets: inherit

  job-next-14-solana-no-wallet-adapter:
    name: "Next14 webpack Solana No wallet adapter"
    needs: check-version
    uses: ./.github/workflows/test-example-app.yml
    with:
      project-path: packages/civic-auth-web3/solana/next14-no-wallet-adapter
      cypress-spec: cypress/e2e/features/example-apps/solana-next14-no-wa-login.feature
    secrets: inherit

  job-next-15-turbopack-solana-wallet-adapter:
    name: "Next15 webpack Solana wallet adapter (Turbopack)"
    needs: check-version
    uses: ./.github/workflows/test-example-app.yml
    with:
      project-path: packages/civic-auth-web3/solana/next15-wallet-adapter
      cypress-spec: cypress/e2e/features/example-apps/solana-next15-turbopack-wa-login.feature
      build-command: "yarn build-turbopack"
    secrets: inherit

  job-next-15-webpack-solana-wallet-adapter:
    name: "Next15 webpack Solana wallet adapter (Webpack)"
    needs: check-version
    uses: ./.github/workflows/test-example-app.yml
    with:
      project-path: packages/civic-auth-web3/solana/next15-wallet-adapter
      cypress-spec: cypress/e2e/features/example-apps/solana-next15-wa-login.feature
    secrets: inherit

  job-next-15-turbopack-no-solana-wallet-adapter:
    name: "Next15 webpack no Solana wallet adapter (Turbopack)"
    needs: check-version
    uses: ./.github/workflows/test-example-app.yml
    with:
      project-path: packages/civic-auth-web3/solana/next15-no-wallet-adapter
      cypress-spec: cypress/e2e/features/example-apps/solana-next15-turbopack-no-wa-login.feature
      build-command: "yarn build-turbopack"
    secrets: inherit

  job-next-15-webpack-no-solana-wallet-adapter:
    name: "Next15 webpack no Solana wallet adapter (Webpack)"
    needs: check-version
    uses: ./.github/workflows/test-example-app.yml
    with:
      project-path: packages/civic-auth-web3/solana/next15-no-wallet-adapter
      cypress-spec: cypress/e2e/features/example-apps/solana-next15-no-wa-login.feature
    secrets: inherit

  job-vite-solana-wallet-adapter:
    name: "Vite solana wallet adapter"
    needs: check-version
    uses: ./.github/workflows/test-example-app.yml
    with:
      project-path: packages/civic-auth-web3/solana/vite-wallet-adapter
      cypress-spec: cypress/e2e/features/example-apps/solana-vite-wa-login.feature
    secrets: inherit

  job-vite-no-solana-wallet-adapter:
    name: "Vite no solana wallet adapter"
    needs: check-version
    uses: ./.github/workflows/test-example-app.yml
    with:
      project-path: packages/civic-auth-web3/solana/vite-no-wallet-adapter
      cypress-spec: cypress/e2e/features/example-apps/solana-vite-no-wa-login.feature
    secrets: inherit

  job-vite-wagmi-example-app:
    name: "Vite wagmi example app"
    needs: check-version
    uses: ./.github/workflows/test-example-app.yml
    with:
      project-path: packages/civic-auth-web3/wagmi
      cypress-spec: cypress/e2e/features/example-apps/wagmi-login.feature
    secrets: inherit

  # Development jobs
  job-nextjs-example-app-dev:
    name: "(Dev Mode) Nextjs example app"
    needs: check-version
    uses: ./.github/workflows/test-example-app-dev.yml
    with:
      project-path: packages/civic-auth/nextjs
      cypress-spec: |
        cypress/e2e/features/example-apps/nextjs-login.feature
        cypress/e2e/features/example-apps/nextjs-custom-login.feature
    secrets: inherit

  job-reactjs-example-app-dev:
    name: "(Dev Mode) Reactjs example app"
    needs: check-version
    uses: ./.github/workflows/test-example-app-dev.yml
    with:
      project-path: packages/civic-auth/reactjs
      cypress-spec: |
        cypress/e2e/features/example-apps/reactjs-login.feature
        cypress/e2e/features/example-apps/reactjs-custom-login.feature
    secrets: inherit

  job-express-example-app-dev:
    name: "(Dev Mode) Express example app"
    needs: check-version
    uses: ./.github/workflows/test-example-app-dev.yml
    with:
      project-path: packages/civic-auth/server/express
      cypress-spec: cypress/e2e/features/example-apps/express-login.feature
    secrets: inherit

  job-fastify-example-app-dev:
    name: "(Dev Mode) Fastify example app"
    needs: check-version
    uses: ./.github/workflows/test-example-app-dev.yml
    with:
      project-path: packages/civic-auth/server/fastify
      cypress-spec: cypress/e2e/features/example-apps/fastify-login.feature
    secrets: inherit

  job-hono-example-app-dev:
    name: "(Dev Mode) Hono example app"
    needs: check-version
    uses: ./.github/workflows/test-example-app-dev.yml
    with:
      project-path: packages/civic-auth/server/hono
      cypress-spec: cypress/e2e/features/example-apps/hono-login.feature
    secrets: inherit

  job-next-14-webpack-solana-wallet-adapter-dev:
    name: "(Dev Mode) Next14 webpack Solana wallet adapter"
    needs: check-version
    uses: ./.github/workflows/test-example-app-dev.yml
    with:
      project-path: packages/civic-auth-web3/solana/next14-wallet-adapter
      cypress-spec: cypress/e2e/features/example-apps/solana-next14-wa-login.feature
    secrets: inherit

  job-next-14-solana-no-wallet-adapter-dev:
    name: "(Dev Mode) Next14 webpack Solana No wallet adapter"
    needs: check-version
    uses: ./.github/workflows/test-example-app-dev.yml
    with:
      project-path: packages/civic-auth-web3/solana/next14-no-wallet-adapter
      cypress-spec: cypress/e2e/features/example-apps/solana-next14-no-wa-login.feature
    secrets: inherit

  job-next-15-turbopack-solana-wallet-adapter-dev:
    name: "(Dev Mode) Next15 webpack Solana wallet adapter (Turbopack)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-dev.yml
    with:
      project-path: packages/civic-auth-web3/solana/next15-wallet-adapter
      cypress-spec: cypress/e2e/features/example-apps/solana-next15-turbopack-wa-login.feature
    secrets: inherit

  job-next-15-webpack-solana-wallet-adapter-dev:
    name: "(Dev Mode) Next15 Solana wallet adapter (Webpack)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-dev.yml
    with:
      project-path: packages/civic-auth-web3/solana/next15-wallet-adapter
      cypress-spec: cypress/e2e/features/example-apps/solana-next15-wa-login.feature
    secrets: inherit

  job-next-15-turbopack-no-solana-wallet-adapter-dev:
    name: "(Dev Mode) Next15 webpack no Solana wallet adapter (Turbopack)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-dev.yml
    with:
      project-path: packages/civic-auth-web3/solana/next15-no-wallet-adapter
      cypress-spec: cypress/e2e/features/example-apps/solana-next15-turbopack-no-wa-login.feature
    secrets: inherit

  job-next-15-webpack-no-solana-wallet-adapter-dev:
    name: "(Dev Mode) Next15 webpack no Solana wallet adapter (Webpack)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-dev.yml
    with:
      project-path: packages/civic-auth-web3/solana/next15-no-wallet-adapter
      cypress-spec: cypress/e2e/features/example-apps/solana-next15-no-wa-login.feature
    secrets: inherit

  job-vite-solana-wallet-adapter-dev:
    name: "(Dev Mode) Vite solana wallet adapter"
    needs: check-version
    uses: ./.github/workflows/test-example-app-dev.yml
    with:
      project-path: packages/civic-auth-web3/solana/vite-wallet-adapter
      cypress-spec: cypress/e2e/features/example-apps/solana-vite-wa-login.feature
    secrets: inherit

  job-vite-no-solana-wallet-adapter-dev:
    name: "(Dev Mode) Vite no solana wallet adapter"
    needs: check-version
    uses: ./.github/workflows/test-example-app-dev.yml
    with:
      project-path: packages/civic-auth-web3/solana/vite-no-wallet-adapter
      cypress-spec: cypress/e2e/features/example-apps/solana-vite-no-wa-login.feature
    secrets: inherit

  job-vite-wagmi-example-app-dev:
    name: " (Dev Mode) Vite wagmi example app"
    needs: check-version
    uses: ./.github/workflows/test-example-app-dev.yml
    with:
      project-path: packages/civic-auth-web3/wagmi
      cypress-spec: cypress/e2e/features/example-apps/wagmi-login.feature
    secrets: inherit