name: NextJS Build and Dev

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4

      - name: Install Bun (used to run the examples)
        uses: oven-sh/setup-bun@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies'
        shell: bash
        run: yarn install --frozen-lockfile
        
      - name: Build
        run: yarn build
        
      - name: Start dev server
        uses: JarvusInnovations/background-action@v1.0.7  
        with:
          run: yarn dev &
          working-directory: ./
          wait-on: http://localhost:3000
          wait-for: 120s
