name: Build and run example apps

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: bc915ff0-9e27-4a09-96a9-963649f9b025
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4

      - name: Install Bun (used to run the examples)
        uses: oven-sh/setup-bun@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies'
        shell: bash
        run: yarn install --frozen-lockfile
        
      - name: Build
        run: yarn build
        
      - name: Start the nextjs example app
        uses: JarvusInnovations/background-action@v1.0.7
        with:
          run: yarn dev &
          working-directory: packages/civic-auth/nextjs
          wait-on: http://localhost:3000
          wait-for: 60s
          log-output-if: true

      - name: Start the reactjs example app
        uses: JarvusInnovations/background-action@v1.0.7
        with:
          run: yarn dev &
          working-directory: packages/civic-auth/reactjs
          wait-on: http://localhost:3006
          wait-for: 60s
          log-output-if: true

      - name: Start the express example app
        uses: JarvusInnovations/background-action@v1.0.7
        with:
          run: yarn dev &
          working-directory: packages/civic-auth/server/express
          wait-on: http://localhost:3007
          wait-for: 60s
          log-output-if: true

      - name: Start the fastify example app
        uses: JarvusInnovations/background-action@v1.0.7
        with:
          run: yarn dev &
          working-directory: packages/civic-auth/server/fastify
          wait-on: http://localhost:3008
          wait-for: 60s
          log-output-if: true

      - name: Start the hono example app
        uses: JarvusInnovations/background-action@v1.0.7
        with:
          run: yarn dev &
          working-directory: packages/civic-auth/server/hono
          wait-on: http://localhost:3009
          wait-for: 60s
          log-output-if: true