name: Publish Combined Allure Reports

on:
  workflow_dispatch:
    inputs:
      target-sha:
        description: 'Target SHA to collect reports from (defaults to latest main)'
        required: false
        type: string
  push:
    branches:
      - chore/update_web3_tests
      - main

jobs:
  publish-combined-reports:
    name: "Publish Combined Allure Reports"
    runs-on: ubuntu-latest
    if: always()
    permissions:
      contents: write
      actions: read
      id-token: write
      pages: write
    steps:
      - name: Debug trigger information
        run: |
          echo "🚀 Workflow triggered successfully!"
          echo "Event: ${{ github.event_name }}"
          echo "Triggered by workflow: ${{ github.event.workflow_run.name || 'N/A' }}"
          echo "SHA: ${{ github.event.workflow_run.head_sha || github.sha }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch || github.ref_name }}"
          
      - name: Wait for test workflows to complete
        run: |
          echo "⏳ Waiting for test workflows to complete..."
          echo "This workflow will wait up to 30 minutes for test workflows to finish"
          
          # Wait for test workflows to complete
          timeout=1800  # 30 minutes
          elapsed=0
          interval=30   # Check every 30 seconds
          
          while [ $elapsed -lt $timeout ]; do
            echo "Checking for completed test workflows... (${elapsed}s elapsed)"
            
            # Check if we have any completed test workflows with artifacts
            if gh run list --workflow="web2-e2e-tests-playwright-dev-mode.yml" --limit=1 --json status,conclusion | jq -r '.[0].conclusion' | grep -q "success\|failure"; then
              echo "✅ Found completed test workflows, proceeding with publish"
              break
            fi
            
            sleep $interval
            elapsed=$((elapsed + interval))
          done
          
          if [ $elapsed -ge $timeout ]; then
            echo "⚠️ Timeout reached, proceeding anyway (some workflows may still be running)"
          fi
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Web2 Dev Mode Report
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: web2-e2e-tests-playwright-dev-mode.yml
          name: web2-dev-mode-allure-report
          path: reports/web2-dev-mode/
          if_no_artifact_found: warn

      - name: Download Web2 Start Mode Report
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: web2-e2e-tests-playwright-start-mode.yml
          name: web2-start-mode-allure-report
          path: reports/web2-start-mode/
          if_no_artifact_found: warn

      - name: Download Web3 Dev Mode Report
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: web3-e2e-tests-playwright-dev-mode.yml
          name: web3-dev-mode-allure-report
          path: reports/web3-dev-mode/
          if_no_artifact_found: warn

      - name: Download Web3 Start Mode Report
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: web3-e2e-tests-playwright-start-mode.yml
          name: web3-start-mode-allure-report
          path: reports/web3-start-mode/
          if_no_artifact_found: warn

      - name: List downloaded reports
        run: |
          echo "Downloaded reports structure:"
          find reports -type f -name "index.html" | head -10
          echo "Total report directories found: $(find reports -name index.html | wc -l)"
          ls -la reports/

      - name: Create combined report structure
        run: |
          echo "Creating combined report structure..."
          mkdir -p combined-report
          
          # Create an index.html that provides navigation to all reports
          cat > combined-report/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Civic Auth E2E Test Reports</title>
              <style>
                  body { 
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                      margin: 0; padding: 40px; 
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      min-height: 100vh;
                      color: white;
                  }
                  .container { 
                      max-width: 1200px; 
                      margin: 0 auto; 
                      background: rgba(255,255,255,0.1);
                      backdrop-filter: blur(10px);
                      border-radius: 20px;
                      padding: 40px;
                      box-shadow: 0 8px 32px rgba(0,0,0,0.3);
                  }
                  h1 { 
                      text-align: center; 
                      margin-bottom: 40px; 
                      font-size: 2.5em;
                      text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
                  }
                  .reports-grid { 
                      display: grid; 
                      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); 
                      gap: 30px; 
                  }
                  .report-card { 
                      background: rgba(255,255,255,0.15);
                      border-radius: 15px; 
                      padding: 30px; 
                      text-align: center;
                      transition: all 0.3s ease;
                      border: 1px solid rgba(255,255,255,0.2);
                  }
                  .report-card:hover { 
                      transform: translateY(-10px);
                      background: rgba(255,255,255,0.25);
                      box-shadow: 0 15px 35px rgba(0,0,0,0.3);
                  }
                  .report-card h2 { 
                      margin-bottom: 20px; 
                      font-size: 1.4em;
                  }
                  .report-card a { 
                      display: inline-block;
                      background: rgba(255,255,255,0.9);
                      color: #333;
                      padding: 12px 30px;
                      border-radius: 25px;
                      text-decoration: none;
                      font-weight: 600;
                      transition: all 0.3s ease;
                  }
                  .report-card a:hover { 
                      background: white;
                      transform: scale(1.05);
                  }
                  .emoji { font-size: 2em; margin-bottom: 15px; }
                  .description { 
                      margin: 15px 0; 
                      opacity: 0.9; 
                      font-size: 0.95em;
                      line-height: 1.4;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🧪 Civic Auth E2E Test Reports</h1>
                  <div class="reports-grid">
                      <div class="report-card">
                          <div class="emoji">🚀</div>
                          <h2>Web2 Dev Mode</h2>
                          <div class="description">Development mode tests for Web2 applications including NextJS, React, Express, and VanillaJS</div>
                          <a href="web2-dev-mode/index.html">View Report</a>
                      </div>
                      <div class="report-card">
                          <div class="emoji">🏭</div>
                          <h2>Web2 Start Mode</h2>
                          <div class="description">Production build tests for Web2 applications with optimized bundles and performance validation</div>
                          <a href="web2-start-mode/index.html">View Report</a>
                      </div>
                      <div class="report-card">
                          <div class="emoji">🌐</div>
                          <h2>Web3 Dev Mode</h2>
                          <div class="description">Development mode tests for Web3 applications including Solana wallet adapters and Wagmi integrations</div>
                          <a href="web3-dev-mode/index.html">View Report</a>
                      </div>
                      <div class="report-card">
                          <div class="emoji">⚡</div>
                          <h2>Web3 Start Mode</h2>
                          <div class="description">Production build tests for Web3 applications with wallet connectivity and blockchain interactions</div>
                          <a href="web3-start-mode/index.html">View Report</a>
                      </div>
                  </div>
              </div>
          </body>
          </html>
          EOF

      - name: Copy individual reports to combined structure
        run: |
          echo "Copying individual reports..."
          
          # Copy each report to the combined structure
          # We need to copy the main report files (index.html and supporting files) 
          # not the nested numbered directories
          
          copy_main_report() {
            local source_dir="$1"
            local target_dir="$2"
            local report_name="$3"
            
            if [ -d "$source_dir" ]; then
              mkdir -p "$target_dir"
              
              # Copy main report files (index.html, styles.css, etc.) but skip numbered directories
              if [ -f "$source_dir/index.html" ]; then
                cp "$source_dir/index.html" "$target_dir/"
                [ -f "$source_dir/styles.css" ] && cp "$source_dir/styles.css" "$target_dir/"
                [ -f "$source_dir/favicon.ico" ] && cp "$source_dir/favicon.ico" "$target_dir/"
                [ -d "$source_dir/data" ] && cp -r "$source_dir/data" "$target_dir/"
                [ -d "$source_dir/history" ] && cp -r "$source_dir/history" "$target_dir/"
                [ -d "$source_dir/widgets" ] && cp -r "$source_dir/widgets" "$target_dir/"
                [ -d "$source_dir/plugin" ] && cp -r "$source_dir/plugin" "$target_dir/"
                [ -d "$source_dir/export" ] && cp -r "$source_dir/export" "$target_dir/"
                echo "✅ Copied $report_name report"
              else
                echo "⚠️ No main index.html found in $source_dir, created empty directory"
              fi
            else
              mkdir -p "$target_dir"
              echo "⚠️ $report_name report not found, created empty directory"
            fi
          }
          
          copy_main_report "reports/web2-dev-mode" "combined-report/web2-dev-mode" "Web2 Dev Mode"
          copy_main_report "reports/web2-start-mode" "combined-report/web2-start-mode" "Web2 Start Mode"  
          copy_main_report "reports/web3-dev-mode" "combined-report/web3-dev-mode" "Web3 Dev Mode"
          copy_main_report "reports/web3-start-mode" "combined-report/web3-start-mode" "Web3 Start Mode"
          
          echo "Combined report structure:"
          find combined-report -name "index.html" | sort

      - name: Publish combined reports
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: combined-report
