name: Build and run example apps in Safari

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      publish-allure-to-pages:
        description: 'Publish Allure reports to GitHub Pages'
        required: false
        default: false
        type: boolean
    
jobs:
  check-version:
    uses: ./.github/workflows/check-versions.yml

  # Production jobs with Safari browser
  # NOTE: To enable Allure reports with GitHub Pages, replace these jobs
  # with calls to ./.github/workflows/allure-report-publish.yml
  # and set publish-to-pages: ${{ github.event.inputs.publish-allure-to-pages == 'true' || github.ref == 'refs/heads/main' }}
  job-nextjs-example-app-safari:
    name: "Nextjs example app (Safari)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-playwright.yml
    with:
      project-path: packages/civic-auth/nextjs
      playwright-spec: playwright/tests/nextjs-login.spec.ts
      browser: webkit
    secrets: inherit

  job-reactjs-example-app-safari:
    name: "Reactjs example app (Safari)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-playwright.yml
    with:
      project-path: packages/civic-auth/reactjs
      playwright-spec: playwright/tests/reactjs-login.spec.ts
      browser: webkit
    secrets: inherit

  job-express-example-app-safari:
    name: "Express example app (Safari)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-playwright.yml
    with:
      project-path: packages/civic-auth/server/express
      playwright-spec: playwright/tests/express-login.spec.ts
      browser: webkit
    secrets: inherit

  job-fastify-example-app-safari:
    name: "Fastify example app (Safari)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-playwright.yml
    with:
      project-path: packages/civic-auth/server/fastify
      playwright-spec: playwright/tests/fastify-login.spec.ts
      browser: webkit
    secrets: inherit

  job-hono-example-app-safari:
    name: "Hono example app (Safari)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-playwright.yml
    with:
      project-path: packages/civic-auth/server/hono
      playwright-spec: playwright/tests/hono-login.spec.ts
      browser: webkit
    secrets: inherit

  job-vanillajs-example-app-safari:
    name: "VanillaJS example app (Safari)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-playwright.yml
    with:
      project-path: packages/civic-auth/vanillajs
      playwright-spec: playwright/tests/vanillajs-login.spec.ts
      browser: webkit
    secrets: inherit

  # job-vanillajs-modal-example-app-safari:
  #   name: "VanillaJS Modal example app (Safari)"
  #   needs: check-version
  #   uses: ./.github/workflows/test-example-app-playwright.yml
  #   with:
  #     project-path: packages/civic-auth/vanillajs
  #     playwright-spec: playwright/tests/vanillajs-modal-login.spec.ts
  #     browser: webkit
  #   secrets: inherit

  job-next-14-webpack-solana-wallet-adapter-safari:
    name: "Next14 webpack Solana wallet adapter (Safari)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-playwright.yml
    with:
      project-path: packages/civic-auth-web3/solana/next14-wallet-adapter
      playwright-spec: playwright/tests/solana-next14-wa-login.spec.ts
      browser: webkit
    secrets: inherit

  job-next-14-solana-no-wallet-adapter-safari:
    name: "Next14 webpack Solana No wallet adapter (Safari)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-playwright.yml
    with:
      project-path: packages/civic-auth-web3/solana/next14-no-wallet-adapter
      playwright-spec: playwright/tests/solana-next14-no-wa-login.spec.ts
      browser: webkit
    secrets: inherit

  job-next-15-turbopack-solana-wallet-adapter-safari:
    name: "Next15 turbopack Solana wallet adapter (Safari)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-playwright.yml
    with:
      project-path: packages/civic-auth-web3/solana/next15-wallet-adapter
      playwright-spec: playwright/tests/solana-next15-turbopack-wa-login.spec.ts
      build-command: "yarn build-turbopack"
      browser: webkit
    secrets: inherit

  job-next-15-webpack-solana-wallet-adapter-safari:
    name: "Next15 webpack Solana wallet adapter (Safari)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-playwright.yml
    with:
      project-path: packages/civic-auth-web3/solana/next15-wallet-adapter
      playwright-spec: playwright/tests/solana-next15-wa-login.spec.ts
      browser: webkit
    secrets: inherit

  job-next-15-turbopack-no-solana-wallet-adapter-safari:
    name: "Next15 turbopack no Solana wallet adapter (Safari)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-playwright.yml
    with:
      project-path: packages/civic-auth-web3/solana/next15-no-wallet-adapter
      playwright-spec: playwright/tests/solana-next15-turbopack-no-wa-login.spec.ts
      build-command: "yarn build-turbopack"
      browser: webkit
    secrets: inherit

  job-next-15-webpack-no-solana-wallet-adapter-safari:
    name: "Next15 webpack no Solana wallet adapter (Safari)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-playwright.yml
    with:
      project-path: packages/civic-auth-web3/solana/next15-no-wallet-adapter
      playwright-spec: playwright/tests/solana-next15-no-wa-login.spec.ts
      browser: webkit
    secrets: inherit

  job-vite-solana-wallet-adapter-safari:
    name: "Vite solana wallet adapter (Safari)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-playwright.yml
    with:
      project-path: packages/civic-auth-web3/solana/vite-wallet-adapter
      playwright-spec: playwright/tests/solana-vite-wa-login.spec.ts
      browser: webkit
    secrets: inherit

  job-vite-no-solana-wallet-adapter-safari:
    name: "Vite no solana wallet adapter (Safari)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-playwright.yml
    with:
      project-path: packages/civic-auth-web3/solana/vite-no-wallet-adapter
      playwright-spec: playwright/tests/solana-vite-no-wa-login.spec.ts
      browser: webkit
    secrets: inherit

  job-vite-wagmi-example-app-safari:
    name: "Vite wagmi example app (Safari)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-playwright.yml
    with:
      project-path: packages/civic-auth-web3/wagmi
      playwright-spec: playwright/tests/wagmi-login.spec.ts
      browser: webkit
    secrets: inherit 

  job-wagmi-nextjs-example-app-safari:
    name: "Wagmi nextjs example app (Safari)"
    needs: check-version
    uses: ./.github/workflows/test-example-app-playwright.yml
    with:
      project-path: packages/civic-auth-web3/wagmi-nextjs
      playwright-spec: playwright/tests/wagmi-nextjs-login.spec.ts
      browser: webkit
    secrets: inherit

  publish-allure-reports:
    name: "Publish Allure Reports"
    needs: [
      job-nextjs-example-app-safari,
      job-reactjs-example-app-safari,
      job-express-example-app-safari,
      job-fastify-example-app-safari,
      job-hono-example-app-safari,
      job-vanillajs-example-app-safari,
      job-next-14-webpack-solana-wallet-adapter-safari,
      job-next-14-solana-no-wallet-adapter-safari,
      job-next-15-turbopack-solana-wallet-adapter-safari,
      job-next-15-webpack-solana-wallet-adapter-safari,
      job-next-15-turbopack-no-solana-wallet-adapter-safari,
      job-next-15-webpack-no-solana-wallet-adapter-safari,
      job-vite-solana-wallet-adapter-safari,
      job-vite-no-solana-wallet-adapter-safari,
      job-vite-wagmi-example-app-safari,
      job-wagmi-nextjs-example-app-safari
    ]
    runs-on: ubuntu-latest
    if: always()
    permissions:
      contents: write
      actions: read
      id-token: write
      pages: write
    steps:
      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          pattern: allure-results-*
          merge-multiple: true
          path: allure-results

      - name: Load test report history
        if: always()
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Debug gh-pages contents
        if: always()
        run: |
          echo "Contents of gh-pages directory:"
          ls -la gh-pages/ || echo "gh-pages directory not found"
          echo ""
          echo "Looking for allure-history:"
          ls -la gh-pages/allure-history/ 2>/dev/null || echo "allure-history not found"
          echo ""
          echo "Looking for allure-reports:"
          ls -la gh-pages/allure-reports/ 2>/dev/null || echo "allure-reports not found"

      - name: Build test report
        if: always()
        uses: simple-elf/allure-report-action@v1.7
        with:
          gh_pages: gh-pages
          allure_results: allure-results
          allure_history: allure-results
          
      - name: Publish test report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-results
          destination_dir: allure-results
