name: Reusable Build and Test Example App (Dev Mode)

on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string
      cypress-spec:
        required: true
        type: string
    secrets:
      CLIENT_ID:
        required: true
      AUTH_SERVER:
        required: true
      NEXT_PUBLIC_WALLET_API_BASE_URL:
        required: true
      VITE_WALLET_API_BASE_URL:
        required: true
      GH_PAT:
        required: true
      CYPRESS_RECORD_KEY:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      VITE_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CYPRESS_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      AUTH_SERVER: ${{ secrets.AUTH_SERVER }}
      VITE_AUTH_SERVER: ${{ secrets.AUTH_SERVER }}
      NEXT_PUBLIC_WALLET_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_WALLET_API_BASE_URL }}
      VITE_WALLET_API_BASE_URL: ${{ secrets.VITE_WALLET_API_BASE_URL }}
    defaults:
      run:
        working-directory: ${{ inputs.project-path }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Install Bun
        if: contains(inputs.project-path, 'hono')
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "BUN_INSTALL=$HOME/.bun" >> $GITHUB_ENV
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Cache Yarn packages
        uses: actions/cache@v4
        with:
          path: ${{ inputs.project-path }}/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles(format('{0}/yarn.lock', inputs.project-path)) }}-${{ hashFiles(format('{0}/package.json', inputs.project-path)) }}

      - name: Yarn install with latest Civic packages
        run: |
          # Function to get latest version (comparing stable vs beta)
          get_latest_version() {
            local pkg=$1
            local beta_version=$(npm view ${pkg}@beta version 2>/dev/null || echo "0.0.0")
            local stable_version=$(npm view ${pkg} version 2>/dev/null || echo "0.0.0")
            local beta_base=$(echo $beta_version | sed 's/-beta.*//')
            
            # Use beta if its base version is higher than stable
            if [[ $(echo -e "$beta_base\n$stable_version" | sort -V | tail -n 1) == "$beta_base" && "$beta_base" != "$stable_version" ]]; then
              echo "${pkg}@${beta_version}"
            else
              echo "${pkg}@${stable_version}"
            fi
          }
          
          # Check which Civic packages are dependencies and install latest versions
          if grep -q '"@civic/auth"' package.json; then
            auth_pkg=$(get_latest_version "@civic/auth")
            echo "Installing $auth_pkg"
            yarn add "$auth_pkg"
          fi
          
          if grep -q '"@civic/auth-web3"' package.json; then
            web3_pkg=$(get_latest_version "@civic/auth-web3")
            echo "Installing $web3_pkg"
            yarn add "$web3_pkg"
          fi
          
          # Install remaining dependencies
          yarn install

      - name: Start App in Dev Mode
        run: yarn dev &

      - name: Wait for app to start
        run: npx wait-on http-get://localhost:3000 --timeout 300000

      - name: Run Cypress Tests
        id: cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: packages/e2e
          spec: ${{ inputs.cypress-spec }}
          browser: chrome
          install: true
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Send Slack Notification on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "channel": "#build",
              "text": "<!subteam^S012Q4F3TRB> <@UCBGV5J12> Example repo Cypress tests failed in civicteam/civic-auth-examples.\n\nThese tests are run after new beta and prod versions of civic/auth and civic/auth-web3, so there may be an issue with the new version(s). Check the recording of the test failure here https://cloud.cypress.io/projects/cmyigw/runs.\n\n Alternatively, see the full GitHub Actions run details here ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK 